name: Deploy to PyPi
run-name: Deploy to PyPi
on:
  push:
    branches:
      - master
jobs:
  Build-Package:
    runs-on: ubuntu-latest
    steps:
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install Python Dependencies
        run: |
          pip install --upgrade pip
          pip install wheel
          pip install twine
          pip install setuptools
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Build Package
        run: python3 setup.py sdist bdist_wheel
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."